[project]
name = "vcard-generator"
version = "0.1.0"
description = "vCard (VCF) Generator"
requires-python = ">=3.11"

dependencies = [
    "python-fasthtml",
    "MonsterUI",
    "uvicorn"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"