name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install zbar system library
      run: |
        sudo apt-get update
        sudo apt-get install -y libzbar0

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv pip install --system -e ".[dev]"

    - name: Run unit tests
      run: |
        pytest test_vcard.py -v --tb=short

    - name: Upload unit test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-results
        path: |
          .pytest_cache/
          *.log
        if-no-files-found: ignore

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests  # Run integration tests only if unit tests pass

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install integration test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv pip install --system -e ".[integration]"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Run integration tests
      run: |
        pytest test_integration.py -v --tb=short

    - name: Upload integration test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: integration-test-results
        path: |
          .pytest_cache/
          *.log
        if-no-files-found: ignore
